# Generated by Django 6.0.2 on 2026-03-26 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='master',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='masters/covers/', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='master',
            name='products_sold',
            field=models.PositiveIntegerField(default=0, verbose_name='Продано товаров'),
        ),
        migrations.AddField(
            model_name='master',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Трек-номер'),
        ),
        migrations.AddField(
            model_name='post',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_posts', to='shop.product', verbose_name='Связанный товар'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.JSONField(blank=True, default=list, verbose_name='Дополнительные фото'),
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.JSONField(blank=True, default=dict, verbose_name='Опции кастомизации'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('moderation', 'На модерации'), ('published', 'Опубликован'), ('rejected', 'Отклонен'), ('archived', 'В архиве')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Ожидает оплаты'), ('paid', 'Оплачен, ожидает подтверждения'), ('processing', 'В обработке'), ('shipped', 'Передан в доставку'), ('completed', 'Завершен'), ('cancelled', 'Отменен'), ('dispute', 'Спор/Арбитраж')], default='awaiting_payment', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Главное фото'),
        ),
    ]
